#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) buffer DataBuf { float data[]; } data_buf;

layout(push_constant) uniform PushConstants
{
  uint  width;
  uint  height;
  float hmin;
  float hmax;
  int   iterations;
  float k;   // smoothing factor
} pc;

void main()
{
  uvec2 gid = gl_GlobalInvocationID.xy;
  if (gid.x >= pc.width || gid.y >= pc.height)
    return;

  uint  idx = gid.y * pc.width + gid.x;
  float v = data_buf.data[idx];

  float hmid = 0.5 * (pc.hmin + pc.hmax);

  for (int i = 0; i < pc.iterations; i++)
  {
    v = hmid - abs(v - hmid);
  }

  data_buf.data[idx] = v;
}
